export const leftButtons = [
    { value: 'AC', className: 'dark', dataKey: 'AC' },
    { value: '±', className: 'dark', dataKey: 'plusMinus' },
    { value: '%', className: 'dark', dataKey: 'percent' },
    { value: '/', className: 'yellow', dataKey: 'divide' },
    { value: '7', className: 'light', dataKey: '7' },
    { value: '8', className: 'light', dataKey: '8' },
    { value: '9', className: 'light', dataKey: '9' },
    { value: 'X', className: 'yellow', dataKey: 'multiply' },
    { value: '4', className: 'light', dataKey: '4' },
    { value: '5', className: 'light', dataKey: '5' },
    { value: '6', className: 'light', dataKey: '6' },
    { value: '-', className: 'yellow', dataKey: 'minus' },
    { value: '1', className: 'light', dataKey: '1' },
    { value: '2', className: 'light', dataKey: '2' },
    { value: '3', className: 'light', dataKey: '3' },
    { value: '+', className: 'yellow', dataKey: 'plus' },
    { value: '0', className: 'light wide-but', dataKey: '0' },
    { value: '.', className: 'light', dataKey: 'dot' },
    { value: '=', className: 'yellow equals', dataKey: 'equals' },
]

export const rightButtons = [
    { value: '(', className: 'dark', dataKey: '(' },
    { value: ')', className: 'dark', dataKey: ')' },
    { value: 'mc', className: 'dark', dataKey: 'mc' },
    { value: 'm+', className: 'dark', dataKey: 'm+' },
    { value: 'm-', className: 'dark', dataKey: 'm-' },
    { value: 'mr', className: 'dark', dataKey: 'mr' },
    { value: '2nd', className: 'dark', dataKey: '2nd' },
    { value: 'x²', className: 'dark', dataKey: 'xpow2' },
    { value: 'x³', className: 'dark', dataKey: 'xpow3' },
    { value: 'xʸ', className: 'dark', dataKey: 'xpowy' },
    { value: 'eˣ', className: 'dark', dataKey: 'epowx' },
    { value: '10ˣ', className: 'dark', dataKey: '10powx' },
    { value: '1/x', className: 'dark', dataKey: '1/x' },
    { value: '²√x', className: 'dark', dataKey: 'sqrtx' },
    { value: '³√x', className: 'dark', dataKey: 'cubertx' },
    { value: 'ʸ√x', className: 'dark', dataKey: 'yrtx' },
    { value: 'ln', className: 'dark', dataKey: 'ln' },
    { value: 'log₁₀', className: 'dark', dataKey: 'log10' },
    { value: '←', className: 'dark backspace', dataKey: 'undo' },
]
