export const leftButtons = [
    { value: 'AC', className: 'dark' },
    { value: '±', className: 'dark' },
    { value: '%', className: 'dark' },
    { value: '/', className: 'yellow' },
    { value: '7', className: 'light' },
    { value: '8', className: 'light' },
    { value: '9', className: 'light' },
    { value: 'X', className: 'yellow' },
    { value: '4', className: 'light' },
    { value: '5', className: 'light' },
    { value: '6', className: 'light' },
    { value: '-', className: 'yellow' },
    { value: '1', className: 'light' },
    { value: '2', className: 'light' },
    { value: '3', className: 'light' },
    { value: '+', className: 'yellow' },
    { value: '0', className: 'light wide-but' },
    { value: '.', className: 'light' },
    { value: '=', className: 'yellow equals' },
]

export const rightButtons = [
    { value: '(', className: 'dark' },
    { value: ')', className: 'dark' },
    { value: 'mc', className: 'dark' },
    { value: 'm+', className: 'dark' },
    { value: 'm-', className: 'dark' },
    { value: 'mr', className: 'dark' },
    { value: '2nd', className: 'dark' },
    { value: 'x²', className: 'dark' },
    { value: 'x³', className: 'dark' },
    { value: 'xʸ', className: 'dark' },
    { value: 'eˣ', className: 'dark' },
    { value: '10ˣ', className: 'dark' },
    { value: '1/x', className: 'dark' },
    { value: '²√x', className: 'dark' },
    { value: '³√x', className: 'dark' },
    { value: 'ʸ√x', className: 'dark' },
    { value: 'ln', className: 'dark' },
    { value: 'log₁₀', className: 'dark' },
]
